In [1]:
import numpy as np

In [15]:
#Matrix 1D
mat1D = np.array([1,2,3,4,5,6,7,8,9,10])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
print(mat1D)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
print(mat1D[0])

1


In [17]:
print(mat1D + 5)

[ 6  7  8  9 10 11 12 13 14 15]


In [19]:
print(mat2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(mat2D[0])
print(mat2D[1])
print(mat2D[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [23]:
print(mat2D[0][2])

3


In [25]:
print(mat2D + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [27]:
print(mat2D * 10)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [31]:
print(mat1D.shape)
print(mat2D.shape)

(10,)
(3, 3)


In [33]:
print(mat1D.size)
print(mat2D.size)

10
9


In [91]:
#Special Matrix 
mZero = np.zeros((3,3))
mIdentity = np.eye((4))
mFull = np.full((4,4),7)
mOne = np.ones((5,4))
mRandomFloat = np.random.rand(5,5)
mRandomInt = np.random.randint(10,101, size=6)

In [67]:
print(mZero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [69]:
print(mIdentity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [71]:
print(mOne)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [101]:
print(mRandomFloat)

[[0.10928824 0.03639285 0.66251773 0.24882406 0.53233658]
 [0.92969234 0.96337225 0.27411276 0.52578624 0.70092564]
 [0.96601357 0.69914618 0.04073163 0.39111491 0.72703993]
 [0.07711565 0.97633871 0.10644309 0.98377542 0.6660435 ]
 [0.14023857 0.23154846 0.66885423 0.47411545 0.29653344]]


In [93]:
print(mRandomInt)

[12 47 54 11 51 66]


In [113]:
x = np.array([2,6,9])
y = np.array([1,3,5])

dotProduct = np.dot(x,y)
addMatrix = np.add(x,y)
minValue = np.min(x)
maxValue = np.max(y)
meanValue = np.mean(y)
medianValue = np.median(y)
stdValue = np.std(y)
print(f"Hasil dari dot Product : {dotProduct}")
print(f"Hasil Penjumlahan Matriks : {addMatrix}")
print(f"Nilai minimum dari{x} : {minValue}")
print(f"Nilai maximum dari{y} : {maxValue}")
print(f"Rata-rata Nilai dari{y} : {meanValue}")
print(f"Nilai median dari{y} : {medianValue}")
print(f"Nilai Deviasi dari{y} : {stdValue}")

Hasil dari dot Product : 65
Hasil Penjumlahan Matriks : [ 3  9 14]
Nilai minimum dari[2 6 9] : 2
Nilai maximum dari[1 3 5] : 5
Rata-rata Nilai dari[1 3 5] : 3.0
Nilai median dari[1 3 5] : 3.0
Nilai Deviasi dari[1 3 5] : 1.632993161855452


In [115]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

reshape = myArray.reshape(9,1)
flatten =myArray.flatten()

print(reshape)
print(flatten)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]


In [131]:
#Filtering
nilaiSiswa = np.array([80,90,60,50,50,100,95])
lulus = nilaiSiswa[nilaiSiswa > 50]
jumlah = lulus.size
print(lulus)
print (f"Jumlah Siswa yang lulus : {jumlah}")

[ 80  90  60 100  95]
Jumlah Siswa yang lulus : 5
